### ISSUE TITLE
Consider using Mandrill for transactional emails

### ISSUE THREAD

**Issue by joshbodily** [JoiaApp/joia_ios#12]
So, I understand that we already use MailChimp for mailing lists.  Apparently, Mandrill is available now as a plugin for MailChimp that let's you create templates for transactional emails.  I think this is going to give us better results than using Rails + AWS b/c the emails will look predictable and better.

@derek-boman Can you create templates for the emails we have discussed thus far and note what the merge vars are for each one

- [ ] Invite email + Join Group Instructions https://github.com/JoiaApp/email/issues/4
- [ ] Daily Summary email https://github.com/JoiaApp/email/issues/2
- [ ] Mention + Invite email (i.e. recipient was mentioned by email, but not already a member of Joia) https://github.com/JoiaApp/email/issues/3
- [ ] Forgot Password #13 
- [ ] Welcome email https://github.com/JoiaApp/email/issues/1

@dansftown You guys already pay for MailChimp, right?  If we "switch" to Mandrill+MailChimp you can roll back the changes in AWS SES back to the free tier.  Hopefully it will be easier to do email w/ MailChimp :crossed_fingers: 

Thanks!

**Comment by joshbodily** [comment]
https://robots.thoughtbot.com/how-to-send-transactional-emails-from-rails-with-mandrill

**Comment by dansftown** [comment]
I'm fine with swithering to Mandrill, Derek, what do you think?

**Comment by derek-boman** [comment]
@joshbodily here is the API key: `i1Eu_yKetF6po1Cm9UhhSw`

**Comment by derek-boman** [comment]
Updating @joshbodily original comment to add links to issues for each email type.
